import type { CardDefinition, PackDefinition } from "../game/types";
import { cardFactory, roll } from "./author";

// One card per nonblank Main row in the supplied Sheet1 CSV. Numeric IDs are
// the original 1-based sheet row numbers, so duplicate titles remain distinct.
// Copy is adapted to the game’s single-sip rule and short, table-readable cards.
const houseCard = cardFactory("house");
const vipCard = cardFactory("vip");

export const houseCards: CardDefinition[] = [
  houseCard(
    "sheet-003",
    "That's Two Beers?",
    "challenge",
    "Roll d6. On 1–3, give 1 sip. On 4–6, give 2.",
    "A playful tavern moment inspired by the supplied card.",
    roll(1, 6, "Give 1 sip on 1–3; give 2 on 4–6."),
  ),
  houseCard(
    "sheet-004",
    "California Sober",
    "sip",
    "Anyone choosing a smoke break takes water. Everyone else takes 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-005",
    "Dog Vision",
    "group",
    "Wearing blue or yellow? Give 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-006",
    "The Game Giveth",
    "sip",
    "Give 1 sip. If The Game Taketh appeared this game, give 2 instead.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-007",
    "The Game Taketh",
    "sip",
    "Take 1 sip. If The Game Giveth appeared this game, take 2 instead.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-008",
    "Fetch",
    "challenge",
    "Find something outside in 30 seconds, or take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-009",
    "Steve's Beans",
    "challenge",
    "Text Steve a compliment about his beans, or take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-010",
    "Caveman",
    "rule",
    "Until your next turn, speak only in grunts. Slip: take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-011",
    "Drink at Ron",
    "challenge",
    "Toast Ron if he is here. Otherwise, call or message him, or take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-012",
    "Maddy Booty",
    "challenge",
    "Roll d20. The group counts to your roll while you hold a pose. Miss it: 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
    roll(
      1,
      20,
      "Hold your pose while the group counts to {total}. Miss it: 1 sip.",
    ),
  ),
  houseCard(
    "sheet-013",
    "Ron Stop",
    "group",
    "Say “Ron, stop” in one breath. Everyone takes 1 sip when you stop.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-014",
    "Medusa",
    "challenge",
    "Make eye contact with someone. Invite them to take 1 sip with you.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-015",
    "Mr Freeze",
    "rule",
    "Touch someone’s shoulder with permission. They freeze until you let go.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-016",
    "Ursaring",
    "sip",
    "Give 1 sip and apologize like a very serious bear.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-017",
    "Send Help",
    "challenge",
    "Convince someone to join you for 1 sip. If nobody does, take 1.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-018",
    "Story Time",
    "challenge",
    "Go clockwise: repeat the story so far and add one word. First mistake takes 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-019",
    "And the Chicks",
    "group",
    "One guy takes 1 sip. Everyone else takes 1 sip together.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-020",
    "Wiener Schnitzel",
    "group",
    "All the dudes at the table take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-021",
    "Disney Movies",
    "category",
    "Clockwise, name Disney movies. No repeats. First to stall takes 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-022",
    "Taco Bell Menu",
    "category",
    "Clockwise, name Taco Bell menu items. No repeats. First to stall takes 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-023",
    "Headache Simulator",
    "challenge",
    "Wear Becca’s glasses for one round, with permission, or take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-024",
    "Wench",
    "rule",
    "You are the drink wench until your next turn. Offer refills when asked.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-025",
    "Things You Lick",
    "category",
    "Clockwise, name things you lick. No repeats. First to stall takes 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-026",
    "Been to Mexico?",
    "sip",
    "Been to Mexico? Take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-027",
    "Michael Mouse",
    "sip",
    "Count the Disney parks you have visited. If any, take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-028",
    "No take, Give",
    "sip",
    "Roll d6. Odd: give 1 sip. Even: give 2.",
    "A playful tavern moment inspired by the supplied card.",
    roll(1, 6, "Odd: give 1 sip. Even: give 2."),
  ),
  houseCard(
    "sheet-029",
    "FMK",
    "challenge",
    "Play FMK with Blink-182, Green Day, and Weezer. Explain your picks.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-030",
    "Potty Mouth",
    "rule",
    "No swearing until the next card. Slip: take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-031",
    "Batrick",
    "sip",
    "Take a sip for Batrick. Make it water if you need a cure.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-032",
    "Rawr XD",
    "rule",
    "Keep T-Rex arms until your next turn. Forget: take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-033",
    "Movie Trilogies",
    "category",
    "Clockwise, name movie trilogies. No repeats. First to stall takes 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-034",
    "Technophoria",
    "group",
    "Touched a phone today? Take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-035",
    "Countries",
    "category",
    "Clockwise, name countries. No repeats. First to stall takes 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-036",
    "Called Same",
    "sip",
    "You called “Same.” Give 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-037",
    "Missed Same",
    "sip",
    "You missed “Same.” Take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-038",
    "The Rock",
    "sip",
    "Take 1 sip. You cannot pass it along.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-039",
    "This Sucks",
    "rule",
    "Buffalo switches hands until the next card. Wrong hand: 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-040",
    "Pokemon",
    "rule",
    "Speak only your first name until your next turn. Slip: 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-041",
    "Hockey Players",
    "category",
    "Clockwise, name hockey players. No repeats. First to stall takes 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-042",
    "Pet that dog",
    "challenge",
    "Pet a dog in the room, if its owner agrees. No dog? Take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-043",
    "QUICK",
    "group",
    "Both hands up! Last person takes 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-044",
    "Points",
    "group",
    "Count to three, then point to someone. Anyone pointed at takes 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-045",
    "Drink, bitch",
    "sip",
    "If you drank on the last card, take 1 more sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-046",
    "Fiend",
    "challenge",
    "Need a nicotine break? Take one. Otherwise, take a water sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-047",
    "Battery Life",
    "challenge",
    "Guess your phone’s battery. Closest guess gives 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-048",
    "Rock, Paper, Scissors",
    "challenge",
    "Challenge someone to rock, paper, scissors. Loser takes 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-049",
    "Mexico v China",
    "group",
    "Thumbs up for Mexican food; down for Chinese. Minority takes 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-050",
    "Flown First Class?",
    "sip",
    "Flown first class? Take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-051",
    "The Cino",
    "sip",
    "Lost money at a casino? Take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-052",
    "Name Pokémon",
    "category",
    "Clockwise, name Pokémon. No repeats. First to stall takes 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-053",
    "Abra like a Slut",
    "rule",
    "Reverse the turn order after this card.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-054",
    "Winnie the Pooh",
    "sip",
    "Take 1 sip, Pooh Bear style.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-055",
    "Could ya just",
    "sip",
    "Take 1 sip. Yeah, just one.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-056",
    "Mt. Krumpit",
    "challenge",
    "Trade your drink for fresh water, if you want. Otherwise, take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-057",
    "I'm an Idiot",
    "challenge",
    "Say “I’m an idiot.” First to reply “You’re an idiot” takes 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-058",
    "Accent",
    "challenge",
    "Speak like a high lord until your next turn. Give 1 sip now.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-059",
    "Bu-bu-buff..",
    "sip",
    "Almost got Buffaloed? Take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-060",
    "Spirit airlines",
    "challenge",
    "Tell your worst vacation story. If the table laughs, give 1 sip; else take 1.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-061",
    "Damn, you're old",
    "group",
    "Oldest at the table takes 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-062",
    "What was that?",
    "challenge",
    "Read your last sent text aloud, or take 1 sip. Skip private messages.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-063",
    "Straight to jail",
    "sip",
    "Take 1 sip. The judge says no passing it along.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-064",
    "Singles",
    "sip",
    "Single? Take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-065",
    "Couples",
    "sip",
    "In a relationship? Take 1 sip for your person.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-066",
    "Reality TV",
    "category",
    "Clockwise, name reality TV series. No repeats. First to stall takes 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-067",
    "Been to Germany?",
    "sip",
    "Been to Germany? Take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-068",
    "Been to Ireland?",
    "sip",
    "Been to Ireland? Take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-069",
    "Been to Italy?",
    "sip",
    "Been to Italy? Take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-070",
    "Been to Paris?",
    "sip",
    "Been to Paris? Take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-071",
    "Been to Canada?",
    "sip",
    "Been to Canada? Take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-072",
    "Been to Thailand?",
    "sip",
    "Been to Thailand? Take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-073",
    "Been to Japan?",
    "sip",
    "Been to Japan? Take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-074",
    "Bathroom Disaster",
    "sip",
    "Had a bathroom disaster? Take 1 sip. At the cabin? Give 1 too.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-076",
    "Big Baby",
    "group",
    "Youngest at the table takes 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-077",
    "Nicetitties",
    "challenge",
    "Say something nice about the person to your right.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-078",
    "Nailed the G",
    "sip",
    "Nailed the G? Give 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-079",
    "Missed the G",
    "sip",
    "Missed the G? Take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-080",
    "Work it",
    "challenge",
    "Do a runway walk for the table.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-081",
    "ABC's",
    "challenge",
    "Say the alphabet backward. Every mistake earns 1 sip, up to 2.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-082",
    "GOALLLL",
    "group",
    "Hold a big “GOAL!” cheer. Everyone takes 1 sip when you stop.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-083",
    "The Overpacker",
    "group",
    "Who overpacks for one night? Vote. They take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-084",
    "The Lurker",
    "group",
    "Who reads the group chat but never replies? Vote. They take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-085",
    "The Note Taker",
    "group",
    "Who uses their notes app most? Vote. They take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-086",
    "Animated Movies",
    "category",
    "Clockwise, name animated movies. No repeats. First to stall takes 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-087",
    "Freddies Sales",
    "category",
    "Clockwise, name sales at Freddies. No repeats. First to stall takes 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-088",
    "Tin Hat Society",
    "challenge",
    "Share one conspiracy theory you actually believe, or one you invented.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-089",
    "Happy Holidays",
    "challenge",
    "Invent a fake holiday in 10 seconds. Miss the deadline: take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-090",
    "Stare down",
    "challenge",
    "Challenge someone to a staring contest. Loser takes 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-091",
    "Goof Dog",
    "rule",
    "Keep your eyes wide open until your next turn. Blink freely when needed.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-092",
    "Shot Caller",
    "group",
    "Who suggests shots most often? Vote. They take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-093",
    "Spelling Contest",
    "challenge",
    "The person on your left gives you a word to spell. Wrong? You sip. Right? They sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-094",
    "Blessing & a Curse",
    "sip",
    "Give 1 sip, then take 1 sip yourself.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-095",
    "Kitchen Things",
    "category",
    "Clockwise, name things in a kitchen. No repeats. First to stall takes 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-096",
    "Knickers",
    "challenge",
    "Guess the underwear color of the person to your right, if they opt in. Miss: 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-097",
    "No Hands",
    "rule",
    "Until your next turn, keep your hands off your cup. You may skip the rule.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-098",
    "Weatherman",
    "challenge",
    "Give a dramatic weather forecast for tonight’s vibes.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-099",
    "No Beer",
    "rule",
    "Until the next card, first to say “beer” takes 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-100",
    "Dare",
    "challenge",
    "Balance an empty cup on your head for 10 seconds, or take 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-101",
    "Banana Peel",
    "rule",
    "Until your next turn, mime peeling your drink like a banana before each sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-102",
    "Vowels",
    "sip",
    "Count the vowels in your name. Take 1 sip if you have any.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-103",
    "US Capitals",
    "category",
    "Clockwise, name US state capitals. No repeats. First to stall takes 1 sip.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-104",
    "Opinions",
    "challenge",
    "Give your most Joe-or-Becca opinion. The table guesses whose it is.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-105",
    "Police Officer",
    "category",
    "Clockwise, name things you should never say to a police officer. First to stall sips.",
    "A playful tavern moment inspired by the supplied card.",
  ),
  houseCard(
    "sheet-106",
    "Debate",
    "challenge",
    "Pick a silly topic. Each side gets 10 seconds to argue. The table votes for a winner.",
    "A playful tavern moment inspired by the supplied card.",
  ),
];

export const customVipCards: CardDefinition[] = [
  vipCard(
    "sheet-003",
    "Fast as Fuck Boi",
    "challenge",
    "The VIP picks someone to say the alphabet in one minute. Miss a letter: take 1 sip.",
    "A quick-footed guest of honor wins a silly tavern challenge.",
  ),
  vipCard(
    "sheet-004",
    "Your Big Night",
    "group",
    "Everyone says something nice about the VIP. Then everyone takes 1 sip.",
    "Friends toast a guest of honor at a cozy tavern table.",
  ),
  vipCard(
    "sheet-005",
    "One Year Older",
    "sip",
    "The VIP gives 1 sip to someone younger, or takes 1 themselves.",
    "A birthday guest holds up one candle in a tavern.",
  ),
  vipCard(
    "sheet-006",
    "It’s Gotta Go",
    "sip",
    "The VIP takes 1 sip, then chooses someone to join them.",
    "A guest of honor shares a final toast before the next card.",
  ),
];

export const housePack: PackDefinition = {
  version: 1,
  id: "house",
  logo: "art/packs/house.svg",
  title: "Ron’s house cards",
  description:
    "103 personal table cards from the original house sheet. Add them to the Core deck for familiar faces and in-jokes.",
  cardIds: houseCards.map((card) => card.id),
};
