import type { CardDefinition, PackDefinition } from "../game/types";
import { cardFactory } from "./author";

// Most Likely To: a vote pack in the spirit of Drunk Stoned or Stupid. Every
// card is one prompt; on three the whole table points, and whoever gets the
// most votes drinks. Cards are standalone: nothing is tallied between cards.
// Prompts are original, written for this table after reviewing the usual
// public "most likely to" lists for range (nights out, embarrassing moments,
// spicy, future predictions, friend-group habits).
//
// IDs are `likely.NNN` by position in this list; append new prompts at the
// end and never reuse a number.
const card = cardFactory("likely");

type Payout = 2 | 3 | "finish" | "shot";
type Prompt = [prompt: string, payout?: Payout];

const prompts: Prompt[] = [
  // --- Nights out --------------------------------------------------------------
  ["text their ex tonight"],
  ["fall asleep first tonight"],
  ["lose their phone before the night ends"],
  ["start a fight with a bouncer", 3],
  ["order a round nobody asked for"],
  ["cry at the bar for no reason"],
  ["wake up somewhere they don't recognize", 3],
  ["drunk-buy something expensive online"],
  ["get kicked out of a bar", 3],
  ["lose a shoe on a night out"],
  ["make best friends in the bathroom line"],
  ['say "one more" and mean six'],
  ["pee somewhere they absolutely shouldn't"],
  ["show up to brunch still drunk"],
  ["shotgun a beer at a wedding", "shot"],
  ["give a toast nobody asked for"],
  ["puke and rally", 3],
  ["grab the karaoke mic uninvited"],
  ["leave their card at the bar"],
  ["drunk-text the group chat a paragraph"],
  ["fall down the stairs and call it a bit"],
  ["hit the drive-through at 3 a.m."],
  ["start drinking before noon on vacation"],
  ["forget a conversation they started"],
  ["tip 50% because they love the bartender"],
  ["go swimming fully clothed"],
  ["try to fight a goose"],
  ['swear they\'re "not even that drunk"'],
  ["still be awake at 4 a.m."],
  ["need to be carried home", "finish"],
  ["lie about how many drinks they've had"],
  ["order the most expensive shot on the menu", "shot"],
  ["dance on a table"],
  ["get cut off by a bartender", 3],
  ["become best friends with the DJ"],
  ["call their mom drunk"],
  ["sneak alcohol into a movie theater"],
  ["mix three liquors in one cup"],
  ["show up to a party empty-handed"],
  ["start a drunk heart-to-heart"],
  ["kiss a stranger at midnight"],
  ["start a conga line"],
  ["end up at an afterparty with strangers"],
  ["nap at a party and wake up for round two"],
  ["order pizza to the bar"],
  ["get a tattoo on a dare", 3],
  ["throw up in an Uber", 3],
  ["insist on one more bar"],
  ["be the last one to leave every party"],
  ["lose their friends and find new ones"],

  // --- Embarrassing ------------------------------------------------------------
  ["lock themselves out of the house"],
  ["get scammed online"],
  ["text the person they were talking about", 3],
  ["reply-all to the whole company"],
  ["get lost with the GPS on"],
  ["miss a flight"],
  ["go to the wrong airport"],
  ["believe a fake headline"],
  ["pay for something that's free"],
  ["lose rock-paper-scissors to a child"],
  ['call a teacher "mom"'],
  ["get sunburned on a cloudy day"],
  ["wear a shirt inside out all day"],
  ["walk into a glass door"],
  ["wave back at someone who wasn't waving"],
  ["get hurt opening a bag of chips"],
  ["push a pull door"],
  ["like a three-year-old photo by accident"],
  ["join a pyramid scheme"],
  ["get a parking ticket in their own driveway"],
  ["burn water"],
  ["send a screenshot to the person in it", 3],
  ["microwave something metal"],
  ["forget their own phone number"],
  ["lose their wallet twice on one trip"],
  ["trip over absolutely nothing"],
  ["set the kitchen on fire"],
  ["fall for an obvious prank"],
  ["get stuck in a revolving door"],
  ["put the wrong fuel in a car"],
  ["butt-dial their boss"],
  ["laugh at a funeral", 3],
  ["forget the name of someone they just met"],
  ['say "you too" when the waiter says enjoy'],
  ["fake-laugh at a joke they didn't get"],
  ["get caught talking to themselves"],
  ["sing the wrong lyrics with full confidence"],
  ["leave the house in slippers by accident"],
  ["search for the keys in their hand"],
  ["get their head stuck in something"],
  ["send a text meant for someone else"],
  ["get caught stalking someone's Instagram"],
  ["wear socks with sandals unironically"],
  ["get locked in a bathroom"],
  ["show up on the wrong day"],
  ["forget why they walked into a room"],
  ["lose a fight with a vending machine"],
  ["go live on social media by accident"],
  ["lose their car in a parking garage"],
  ["call 911 by accident"],

  // --- Stoned ------------------------------------------------------------------
  ["eat an entire pizza alone"],
  ["forget what they were saying mid-sentence"],
  ["rewatch the same show for the tenth time"],
  ["believe in aliens with their whole chest"],
  ["spend 20 minutes choosing a snack"],
  ["have a deep conversation with a dog"],
  ["order delivery twice in one night"],
  ["laugh at nothing for five straight minutes"],
  ["start a conspiracy podcast"],
  ["put the milk in the cupboard"],
  ["pitch a genius business idea at 2 a.m."],
  ["get paranoid about a cop who isn't there"],
  ["watch nature documentaries for fun"],
  ["buy crystals and mean it"],
  ["take three hours to get ready"],
  ["get obsessed with a new hobby for a month"],
  ['reply "lol" to a serious text'],
  ["eat cereal for dinner"],
  ["explain the universe to a bartender"],
  ["name their houseplants"],
  ["get distracted by a bird mid-argument"],
  ['say "bro, what if…" the most'],
  ["play one album all night"],
  ["fall asleep during a movie they picked"],
  ["eat something off the floor"],
  ["own a bong with a name"],
  ["raid someone else's fridge uninvited"],
  ["think they can talk to animals"],
  ["forget their own birthday"],
  ["order half the menu at a drive-through"],

  // --- Spicy -------------------------------------------------------------------
  ["marry someone they met on vacation", 3],
  ["get back with their ex", 3],
  ["fall in love on a dating app in a week"],
  ["date two people at once", 3],
  ["get caught sneaking out of someone's place"],
  ["have a secret OnlyFans", 3],
  ["send a risky photo to the wrong person", "shot"],
  ["hook up with a coworker", 3],
  ["slide into a celebrity's DMs"],
  ["get married in Vegas"],
  ["have a crush on someone in this room", "shot"],
  ["ghost someone after a great date"],
  ["have the weirdest search history", 3],
  ["keep a dating app open just to look"],
  ["write a love letter to a celebrity"],
  ["propose in public"],
  ["cry at a romcom"],
  ["plan the wedding before the second date"],
  ["get walked in on", 3],
  ["flirt their way out of a ticket"],
  ["have a secret second phone"],
  ["date someone twice their age"],
  ["match with a friend's ex", 3],
  ["have a celebrity hall pass ready"],
  ["be the first one here to get married"],
  ["be the last one here to get married"],
  ["elope without telling anyone"],
  ["make out in a public bathroom"],
  ["have had a crush on a cartoon character"],
  ["tattoo a partner's name on themselves", 3],
  ['send a "you up?" text this weekend'],
  ["hook up at a wedding"],
  ["date someone just for their dog"],
  ["get caught skinny-dipping", 3],
  ["fall for the bartender"],
  ["kiss someone in this room tonight", "shot"],
  ["still have their ex's hoodie"],
  ["fake a phone call to escape a date"],
  ["get a lap dance at a bachelor party"],
  ["have a type nobody understands"],

  // --- The future ----------------------------------------------------------------
  ["become famous"],
  ["go to jail", 3],
  ["win the lottery and lose it all"],
  ["become a millionaire"],
  ["move to another country on a whim"],
  ["end up on reality TV"],
  ["start a cult"],
  ["start a business that actually works"],
  ["get canceled online"],
  ["go viral for the wrong reason"],
  ["live to 100"],
  ["get abducted by aliens"],
  ["survive a zombie apocalypse"],
  ["die first in a horror movie"],
  ["run for office"],
  ["write a memoir nobody asked for"],
  ["end up on the news"],
  ["quit their job dramatically", 3],
  ["have ten kids"],
  ["retire first"],
  ["become a crazy cat person"],
  ["run a marathon"],
  ["adopt a pet on a whim"],
  ["get arrested at a protest"],
  ["own a boat they can't afford"],
  ["move back in with their parents"],
  ["become an influencer"],
  ["win a hot dog eating contest"],
  ["end up in witness protection"],
  ["buy a timeshare"],
  ["get a DUI on a lawn mower"],
  ["open a bar"],
  ["star in a commercial"],
  ["become a landlord everyone hates"],
  ["follow a band on tour"],
  ["live in a van by choice"],
  ["show up on a true crime show"],
  ["fake their own death", 3],
  ["get rich on crypto, then lose it"],
  ["get a face tattoo at 50"],

  // --- The group -----------------------------------------------------------------
  ["be late to their own wedding"],
  ["be the group therapist"],
  ["start drama and act surprised"],
  ["know everyone's secrets"],
  ["leak a secret by accident", 3],
  ["cancel plans last minute"],
  ["plan the whole trip and get no thanks"],
  ["forget to pay you back"],
  ["eat the last slice without asking"],
  ["hog the aux"],
  ["take 200 selfies on one trip"],
  ["overpack for a weekend"],
  ["get lost on a group hike"],
  ["complain all trip and have the best time"],
  ["read the group chat and never reply"],
  ["send a five-minute voice memo"],
  ["start a fight in the group chat"],
  ["change the plan at the last second"],
  ["become the main character on vacation"],
  ["make a spreadsheet for the trip"],
  ["fall asleep in the car every time"],
  ["pick the worst restaurant"],
  ["argue with the GPS"],
  ["steal a souvenir from a hotel"],
  ["leave the party without saying goodbye"],
  ["win every argument by yelling"],
  ["talk their way into a VIP section"],
  ["lie on their resume"],
  ["cheat at board games"],
  ["take a game way too seriously"],
  ["flip the board when they lose"],
  ["blame the dice for losing", 3],
  ["read the rules and still not get it"],
  ["keep score when nobody asked"],
  ["bring a lucky charm to game night"],
  ["be the reason we can't go back somewhere", 3],
  ["get banned from a restaurant"],
  ["have a secret talent nobody knows"],
  ["survive on gas station food for a week"],
  ["be talking about this game tomorrow", "finish"],
];

const payoutText = (payout: Payout = 2) =>
  payout === "finish"
    ? "most votes finishes their drink"
    : payout === "shot"
      ? "most votes takes a shot"
      : `most votes drinks ${payout}`;

export const likelyCards: CardDefinition[] = prompts.map(
  ([prompt, payout], index) =>
    card(
      String(index + 1).padStart(3, "0"),
      "Most Likely To",
      "group",
      `${prompt[0].toUpperCase()}${prompt.slice(1)}. Point on three: ${payoutText(payout)}.`,
    ),
);

export const likelyPack: PackDefinition = {
  version: 1,
  id: "likely",
  logo: "art/packs/likely.svg",
  title: "Most Likely To",
  description:
    "Everyone points on three; the table decides who it's talking about.",
  cardIds: likelyCards.map((card) => card.id),
};
