import type { CardDefinition, Category } from "../game/types";
import { cardFactory } from "./author";

/**
 * Original one-card prompts inspired by common party-game formats: quick
 * give/take cards, table votes, categories, word games, charades, bluffing,
 * and short-lived house rules. See docs/STATUS.md for research references.
 * Keep IDs stable: active sessions snapshot their text and order.
 */
type Draft = [
  id: string,
  title: string,
  category: Category,
  rules: string,
  motif: string,
];
const card = cardFactory("core");

const drafts: Draft[] = [
  // Quick sip cards: a little luck and table interaction without bookkeeping.
  [
    "pick-your-poison",
    "Pick Your Poison",
    "sip",
    "Drink 1 or give 1. Say why you chose it.",
    "a forked road of two small mugs",
  ],
  [
    "split-the-bill",
    "Split the Bill",
    "sip",
    "Pick someone. Each of you drinks 1.",
    "two friends dividing a tavern bill",
  ],
  [
    "generous-round",
    "Generous Round",
    "sip",
    "Give 1 sip each to two different players.",
    "a server carrying two tiny cups",
  ],
  [
    "little-treat",
    "Little Treat",
    "sip",
    "Give 1 sip to whoever needs a little treat.",
    "a wrapped sweet beside a cup",
  ],
  [
    "bad-timing",
    "Bad Timing",
    "sip",
    "Last person to check the time drinks 1.",
    "an hourglass tipping beside a mug",
  ],
  [
    "empty-pockets",
    "Empty Pockets",
    "sip",
    "Anyone with no cash on them drinks 1.",
    "an empty coin purse turned inside out",
  ],
  [
    "phone-face-down",
    "Face Down",
    "sip",
    "Anyone with their phone face up drinks 1.",
    "a glowing sending stone turned face down",
  ],
  [
    "receipt-check",
    "Receipt Check",
    "sip",
    "Anyone who kept a receipt today drinks 1.",
    "a long curled tavern receipt",
  ],
  [
    "night-owl",
    "Night Owl",
    "sip",
    "Latest bedtime last night drinks 1.",
    "a sleepy owl perched on a clock",
  ],
  [
    "early-bird",
    "Early Bird",
    "sip",
    "Earliest wake-up today gives 1.",
    "a rooster crowing over an empty cup",
  ],
  [
    "weather-report",
    "Weather Report",
    "sip",
    "Name today's weather in one dramatic word. Anyone who agrees drinks 1.",
    "a tiny storm cloud over a goblet",
  ],
  [
    "hot-take-tax",
    "Hot Take Tax",
    "sip",
    "Give a harmless hot take. Anyone who disagrees drinks 1.",
    "a steaming scroll laid across a table",
  ],
  [
    "agree-to-disagree",
    "Agree to Disagree",
    "sip",
    "Name a food you dislike. Fans of it drink 1.",
    "two diners arguing over a strange pie",
  ],
  [
    "tiny-victory",
    "Tiny Victory",
    "sip",
    "Name a small win from this week. Give 1 to someone who cheers.",
    "a miniature trophy beside a mug",
  ],
  [
    "wrong-address",
    "Wrong Address",
    "sip",
    "Ever gone to the wrong place? Drink 1.",
    "a lost courier at the wrong tavern door",
  ],
  [
    "missed-exit",
    "Missed Exit",
    "sip",
    "Ever missed your stop or exit? Drink 1.",
    "a wagon passing a marked crossroads",
  ],
  [
    "accidental-reply",
    "Reply All",
    "sip",
    "Ever sent a message to the wrong person? Drink 1.",
    "a misdirected paper bird with two letters",
  ],
  [
    "double-booked",
    "Double Booked",
    "sip",
    "Ever agreed to two plans at once? Drink 1.",
    "two invitations pinned to the same calendar day",
  ],
  [
    "lost-the-plot",
    "Lost the Plot",
    "sip",
    "Forgot why you entered a room today? Drink 1.",
    "a puzzled adventurer in a doorway",
  ],
  [
    "spare-key",
    "Spare Key",
    "sip",
    "Ever locked yourself out? Drink 1.",
    "a key left inside a locked cottage",
  ],
  [
    "impulse-buy",
    "Impulse Buy",
    "sip",
    "Bought something silly this month? Drink 1.",
    "a ridiculous trinket in a merchant's hand",
  ],
  [
    "unfinished-project",
    "Half Finished",
    "sip",
    "Have an unfinished hobby project? Drink 1.",
    "a half-built model castle on a table",
  ],
  [
    "forgot-the-name",
    "What's Your Name?",
    "sip",
    "Forgot a name right after hearing it? Drink 1.",
    "a blank name tag pinned to a cloak",
  ],
  [
    "wrong-lyrics",
    "Wrong Lyrics",
    "sip",
    "Sung the wrong lyrics with confidence? Drink 1.",
    "a bard reading a songbook upside down",
  ],
  [
    "one-more-episode",
    "One More Episode",
    "sip",
    "Stayed up for one more episode? Drink 1.",
    "a candle burning beside a stack of story scrolls",
  ],
  [
    "sent-the-draft",
    "Sent the Draft",
    "sip",
    "Sent a message before proofreading it? Drink 1.",
    "a quill fleeing an unfinished letter",
  ],
  [
    "wrong-tab",
    "Wrong Tab",
    "sip",
    "Opened a tab and forgot why? Drink 1.",
    "a browser-like stack of enchanted windows",
  ],
  [
    "forgot-the-bag",
    "Forgot the Bag",
    "sip",
    "Ever left your shopping bag behind? Drink 1.",
    "a lonely cloth bag on a market stall",
  ],
  [
    "quiet-credit",
    "Quiet Credit",
    "sip",
    "Give 1 to someone who helped you recently. Tell them why.",
    "a small medal handed between friends",
  ],
  [
    "cheers-to-that",
    "Cheers to That",
    "sip",
    "Name something worth celebrating. You drink 1; the table may join.",
    "one cup raised under a string of lanterns",
  ],

  // Group reads: broad, observable, and quick to settle.
  [
    "same-shoes",
    "Same Shoes",
    "group",
    "Anyone wearing the same shoe color as the drawer drinks 1.",
    "matching boots under a tavern table",
  ],
  [
    "pocket-check",
    "Pocket Check",
    "group",
    "Anyone carrying a key drinks 1.",
    "keys spilling from several pockets",
  ],
  [
    "glasses-club",
    "Glasses Club",
    "group",
    "Anyone wearing glasses drinks 1. Everyone else gives 1.",
    "a row of spectacles beside cups",
  ],
  [
    "hat-trick",
    "Hat Trick",
    "group",
    "Anyone wearing a hat gives 1. If nobody is, drawer drinks 1.",
    "a rack of odd pointed hats",
  ],
  [
    "sleeve-squad",
    "Sleeve Squad",
    "group",
    "Long sleeves drink 1. Short sleeves give 1.",
    "two adventurers comparing their sleeves",
  ],
  [
    "color-war",
    "Color War",
    "group",
    "Drawer names a color. Anyone wearing it drinks 1.",
    "bright fabric swatches spread on a table",
  ],
  [
    "pet-people",
    "Pet People",
    "group",
    "Anyone with a pet drinks 1. Tell us its name.",
    "a cat and dog guarding a tavern stool",
  ],
  [
    "plant-parent",
    "Plant Parent",
    "group",
    "Anyone keeping a plant alive gives 1.",
    "a thriving potted fern in a window",
  ],
  [
    "window-seat",
    "Window Seat",
    "group",
    "Window-seat people drink 1. Aisle-seat people give 1.",
    "a carriage with window and aisle seats",
  ],
  [
    "sweet-or-salty",
    "Sweet or Salty",
    "group",
    "Vote sweet or salty. Minority drinks 1; ties mean everyone drinks 1.",
    "a pie and pretzel on a balance scale",
  ],
  [
    "tea-or-coffee",
    "Tea or Coffee",
    "group",
    "Vote tea or coffee. Minority gives 1; ties mean drawer drinks 1.",
    "a teapot and coffee pot facing off",
  ],
  [
    "morning-or-night",
    "Morning or Night",
    "group",
    "Vote mornings or nights. Minority drinks 1; ties mean all drink 1.",
    "sun and moon over opposing mugs",
  ],
  [
    "beach-or-mountain",
    "Beach or Mountain",
    "group",
    "Vote beach or mountain. Minority drinks 1; ties mean all drink 1.",
    "a beach umbrella facing a snowy peak",
  ],
  [
    "dogs-or-cats",
    "Dogs or Cats",
    "group",
    "Vote dogs or cats. Minority gives 1; ties mean drawer gives 1.",
    "a dog and cat at either end of a table",
  ],
  [
    "sit-or-dance",
    "Sit or Dance",
    "group",
    "Vote sit or dance. Minority drinks 1; ties mean everyone toasts.",
    "a chair beside dancing boots",
  ],
  [
    "table-twin",
    "Table Twin",
    "group",
    "Find someone with your birth month. Both give 1. No match? Drink 1.",
    "two matching calendar pages",
  ],
  [
    "name-neighbor",
    "Name Neighbor",
    "group",
    "Find the player whose first name is nearest yours in the alphabet. Both drink 1.",
    "two alphabet letters side by side",
  ],
  [
    "same-first-letter",
    "Same Letter",
    "group",
    "Same first initial as the drawer? Drink 1. No match? Drawer gives 1.",
    "matching initials stamped on two mugs",
  ],
  [
    "furthest-away",
    "Long Way Home",
    "group",
    "Who traveled farthest to get here? They give 1.",
    "a winding road ending at a tavern",
  ],
  [
    "closest-to-home",
    "Local Legend",
    "group",
    "Who lives closest to this place? They drink 1.",
    "a cottage just outside the tavern",
  ],
  [
    "last-photo",
    "Last Photo",
    "group",
    "Anyone whose last photo is of food drinks 1.",
    "a painted food portrait in a tiny frame",
  ],
  [
    "unread-count",
    "Unread Count",
    "group",
    "Most unread messages gives 1. No need to show the screen.",
    "a tower of unopened letters",
  ],
  [
    "tabs-open",
    "Open Tabs",
    "group",
    "Most browser tabs open drinks 1. Honor system.",
    "a fan of tiny enchanted windows",
  ],
  [
    "battery-low",
    "Low Battery",
    "group",
    "Lowest phone battery drinks 1. Ties all drink 1.",
    "a dimly glowing sending stone",
  ],
  [
    "playlist-picker",
    "The DJ",
    "group",
    "Who picked the music? They give 1 to a fan.",
    "a bard choosing records beside a lute",
  ],
  [
    "best-seat",
    "Best Seat",
    "group",
    "On three, point to the best seat. Its occupant gives 1.",
    "one lavish chair among plain stools",
  ],
  [
    "worst-seat",
    "Worst Seat",
    "group",
    "On three, point to the worst seat. Its occupant drinks 1.",
    "one wobbly stool among fine chairs",
  ],
  [
    "most-pockets",
    "Pocket Dimension",
    "group",
    "Most pockets on your outfit gives 1.",
    "a coat covered in impossible pockets",
  ],
  [
    "group-selfie",
    "Group Portrait",
    "group",
    "Everyone makes the same silly face. Last to copy drinks 1.",
    "friends posing for a ridiculous portrait",
  ],
  [
    "compliment-chain",
    "Pass It On",
    "group",
    "Compliment the player to your left. They give 1 to someone else.",
    "a glowing compliment scroll passed clockwise",
  ],

  // Specific category starts; first repeat or voluntary pass ends each round.
  [
    "pizza-toppings",
    "Pizza Toppings",
    "category",
    "Name pizza toppings clockwise. First repeat or pass drinks 1.",
    "a pie covered with unlikely toppings",
  ],
  [
    "breakfast-foods",
    "Breakfast Club",
    "category",
    "Name breakfast foods clockwise. First repeat or pass drinks 1.",
    "a sunrise breakfast spread",
  ],
  [
    "things-that-fly",
    "Things That Fly",
    "category",
    "Name things that fly clockwise. First repeat or pass drinks 1.",
    "birds and paper planes above the rafters",
  ],
  [
    "things-with-wheels",
    "On Wheels",
    "category",
    "Name things with wheels clockwise. First repeat or pass drinks 1.",
    "an odd parade of wheeled objects",
  ],
  [
    "fictional-villains",
    "Villain Roll Call",
    "category",
    "Name fictional villains clockwise. First repeat or pass drinks 1.",
    "silhouettes of theatrical storybook villains",
  ],
  [
    "movie-genres",
    "At the Movies",
    "category",
    "Name movie genres clockwise. First repeat or pass drinks 1.",
    "a tiny stage with genre masks",
  ],
  [
    "board-games",
    "Game Shelf",
    "category",
    "Name board games clockwise. First repeat or pass drinks 1.",
    "a shelf overflowing with game boxes",
  ],
  [
    "things-in-a-fridge",
    "Fridge Raid",
    "category",
    "Name things in a fridge clockwise. First repeat or pass drinks 1.",
    "a frosty cupboard full of food",
  ],
  [
    "things-in-a-bag",
    "Bag Check",
    "category",
    "Name things in a bag clockwise. First repeat or pass drinks 1.",
    "a travel bag spilling harmless treasures",
  ],
  [
    "things-at-a-party",
    "Party Inventory",
    "category",
    "Name things at a party clockwise. First repeat or pass drinks 1.",
    "party supplies scattered on a table",
  ],
  [
    "bad-superpowers",
    "Bad Superpowers",
    "category",
    "Invent useless powers clockwise. First repeat or pass drinks 1.",
    "a hero proudly wielding a useless power",
  ],
  [
    "fake-band-names",
    "Fake Band Names",
    "category",
    "Invent band names clockwise. First repeat or pass drinks 1.",
    "a blank concert poster beside instruments",
  ],
  [
    "pet-names",
    "Pet Names",
    "category",
    "Name possible pet names clockwise. First repeat or pass drinks 1.",
    "name tags hanging around a pet bed",
  ],
  [
    "ice-cream-flavors",
    "Ice Cream",
    "category",
    "Name ice cream flavors clockwise. First repeat or pass drinks 1.",
    "colorful scoops in a chilled bowl",
  ],
  [
    "sandwich-fillings",
    "Sandwich Shop",
    "category",
    "Name sandwich fillings clockwise. First repeat or pass drinks 1.",
    "an overflowing sandwich cut in half",
  ],
  [
    "vacation-mishaps",
    "Trip Disasters",
    "category",
    "Name vacation mishaps clockwise. First repeat or pass drinks 1.",
    "a suitcase bursting open at a port",
  ],
  [
    "tavern-jobs",
    "Tavern Payroll",
    "category",
    "Name tavern jobs clockwise. First repeat or pass drinks 1.",
    "a hiring board outside the tavern",
  ],
  [
    "fantasy-pets",
    "Fantasy Pets",
    "category",
    "Invent fantasy pets clockwise. First repeat or pass drinks 1.",
    "tiny fantastical pets peeking from baskets",
  ],
  [
    "things-a-dragon-owns",
    "Dragon's Closet",
    "category",
    "Name things a dragon owns clockwise. First repeat or pass drinks 1.",
    "a dragon's crowded wardrobe",
  ],
  [
    "terrible-quests",
    "Bad Quests",
    "category",
    "Invent terrible quests clockwise. First repeat or pass drinks 1.",
    "a quest board full of absurd notices",
  ],
  [
    "fake-holidays",
    "Fake Holidays",
    "category",
    "Invent holidays clockwise. First repeat or pass drinks 1.",
    "a calendar of strange celebrations",
  ],
  [
    "things-with-keys",
    "Under Lock",
    "category",
    "Name things with keys clockwise. First repeat or pass drinks 1.",
    "a ring of keys beside locked objects",
  ],
  [
    "round-objects",
    "Going in Circles",
    "category",
    "Name round objects clockwise. First repeat or pass drinks 1.",
    "a collection of circular objects",
  ],
  [
    "loud-things",
    "Noise Complaint",
    "category",
    "Name loud things clockwise. First repeat or pass drinks 1.",
    "a ringing bell beside a drum",
  ],
  [
    "tiny-things",
    "Tiny Things",
    "category",
    "Name tiny things clockwise. First repeat or pass drinks 1.",
    "miniature objects on a giant table",
  ],
  [
    "things-that-melt",
    "Meltdown",
    "category",
    "Name things that melt clockwise. First repeat or pass drinks 1.",
    "a melting collection under warm light",
  ],
  [
    "things-that-are-blue",
    "Feeling Blue",
    "category",
    "Name blue things clockwise. First repeat or pass drinks 1.",
    "a pile of different blue objects",
  ],
  [
    "terrible-gifts",
    "Bad Gifts",
    "category",
    "Invent terrible gifts clockwise. First repeat or pass drinks 1.",
    "an unwanted gift in torn wrapping",
  ],
  [
    "three-word-movies",
    "Movie in Three",
    "category",
    "Describe movies in three words clockwise. First repeat or pass drinks 1.",
    "a film reel divided into three panels",
  ],
  [
    "alphabet-food",
    "Alphabet Soup",
    "category",
    "Name foods A to Z clockwise. First blank or pass drinks 1.",
    "letters floating in a soup bowl",
  ],

  // Short challenges with a concrete end; no materials, scoring or timers.
  [
    "one-word-toast",
    "One Word Toast",
    "challenge",
    "Give a toast using exactly one word. Table votes: good or drink 1.",
    "a bard offering one dramatic word",
  ],
  [
    "bad-advice",
    "Bad Advice",
    "challenge",
    "Ask for harmless bad advice. Each player offers one line; pick the best to give 1.",
    "a crooked advice booth",
  ],
  [
    "sell-me-this",
    "Sell Me This",
    "challenge",
    "Pick an object nearby. Sell it to the table in one sentence.",
    "a merchant presenting an ordinary spoon",
  ],
  [
    "new-catchphrase",
    "Catchphrase",
    "challenge",
    "Invent a catchphrase for someone here. They use it once or drink 1.",
    "a scroll with an absurd slogan",
  ],
  [
    "movie-trailer",
    "Movie Trailer",
    "challenge",
    "Narrate this night as a movie trailer. First laugh gives 1.",
    "a storyteller unveiling a dramatic poster",
  ],
  [
    "terrible-review",
    "One Star",
    "challenge",
    "Give a one-star review of a harmless object nearby.",
    "a review scroll with a single star",
  ],
  [
    "five-star-review",
    "Five Stars",
    "challenge",
    "Give a five-star review of the weirdest object nearby.",
    "a review scroll covered in stars",
  ],
  [
    "fake-award",
    "And the Award Goes",
    "challenge",
    "Give someone a ridiculous award. They make an acceptance speech.",
    "a tiny trophy offered to a surprised friend",
  ],
  [
    "press-conference",
    "No Comment",
    "challenge",
    "The table asks one question. Answer like a scandal-hit celebrity.",
    "a nervous hero at a press lectern",
  ],
  [
    "secret-ingredient",
    "Secret Ingredient",
    "challenge",
    "Describe a made-up dish. Table guesses its secret ingredient.",
    "a covered platter concealing a strange dish",
  ],
  [
    "bad-alibi",
    "Bad Alibi",
    "challenge",
    "Explain why you were late to a dragon fight. Table votes if it holds up.",
    "a late knight before a skeptical judge",
  ],
  [
    "perfect-crime",
    "Perfect Crime",
    "challenge",
    "Confess to stealing a harmless object here. Table names your motive.",
    "a missing spoon outlined on a table",
  ],
  [
    "instant-nickname",
    "Instant Nickname",
    "challenge",
    "Give the player on your right a nickname. They approve it or give 1.",
    "a new name tag held up for inspection",
  ],
  [
    "reverse-compliment",
    "Backhanded",
    "challenge",
    "Give a compliment that sounds like an insult. Target judges it.",
    "a rose wrapped in thorny ribbon",
  ],
  [
    "tiny-argument",
    "Petty Debate",
    "challenge",
    "Defend a silly opinion. Table gives 1 if convinced; else you drink 1.",
    "two debaters arguing over a tiny object",
  ],
  [
    "courtroom",
    "Objection",
    "challenge",
    "Accuse someone of a harmless crime. They give one-sentence defense.",
    "a tiny courtroom gavel beside a mug",
  ],
  [
    "haiku",
    "Tavern Haiku",
    "challenge",
    "Make a three-line poem about this table. Everyone snaps or you drink 1.",
    "a poet scribbling three lines",
  ],
  [
    "dramatic-reading",
    "Read the Room",
    "challenge",
    "Read any short label nearby like a dramatic prophecy.",
    "a seer reading a mundane bottle label",
  ],
  [
    "charade-animal",
    "Animal Act",
    "challenge",
    "Act out an animal silently. Each player gets one guess; first correct guess gives 1.",
    "a performer wearing a paper animal mask",
  ],
  [
    "charade-job",
    "What Do I Do?",
    "challenge",
    "Act out a job silently. Each player gets one guess; first correct guess gives 1.",
    "a performer miming an ordinary job",
  ],
  [
    "charade-object",
    "Invisible Prop",
    "challenge",
    "Mime using an object. Each player gets one guess; first correct guess gives 1.",
    "an invisible object outlined by a mime",
  ],
  [
    "reverse-charade",
    "Everyone But You",
    "challenge",
    "Table acts out one animal together. Drawer gets one guess.",
    "friends miming the same animal",
  ],
  [
    "sound-effect",
    "Sound Effects",
    "challenge",
    "Make a sound effect for a nearby object. Each player gets one guess; first correct guess gives 1.",
    "an object sending out exaggerated sound waves",
  ],
  [
    "hum-a-song",
    "Hum It",
    "challenge",
    "Hum a song without lyrics. Each player gets one guess; first correct guess gives 1.",
    "a humming bard with floating notes",
  ],
  [
    "finish-the-line",
    "Finish the Line",
    "challenge",
    "Start a familiar saying. First person to finish it gives 1.",
    "a half-written proverb on a scroll",
  ],
  [
    "two-word-story",
    "Two Word Story",
    "challenge",
    "Begin a story with two words. Each player adds two; stop after one lap.",
    "a storybook filling with two-word lines",
  ],
  [
    "one-sentence-sequel",
    "The Sequel",
    "challenge",
    "Invent a one-sentence sequel to tonight. Table names its title.",
    "a second volume of an imaginary story",
  ],
  [
    "fake-headline",
    "Breaking News",
    "challenge",
    "Make a news headline about this table. Target gives 1 if flattered.",
    "a news sheet with a dramatic headline",
  ],
  [
    "lost-and-found",
    "Lost and Found",
    "challenge",
    "Describe an imaginary lost item. Table guesses its owner.",
    "a lost-property bin full of oddities",
  ],
  [
    "dream-dinner",
    "Dream Dinner",
    "challenge",
    "Name your dream dinner. Anyone who wants it drinks 1.",
    "a feast laid out as one perfect meal",
  ],
  [
    "desert-island",
    "One Item",
    "challenge",
    "Name one item for a deserted island. Table votes if it helps.",
    "one odd tool on a deserted island",
  ],
  [
    "bad-password",
    "Bad Password",
    "challenge",
    "Invent the worst safe-to-say password. Table picks the worst.",
    "a locked chest with an absurd password hint",
  ],
  [
    "fact-check",
    "Fact Check",
    "challenge",
    "State a surprising fact, true or invented. Table guesses; then reveal.",
    "a scholar presenting a dubious chart",
  ],
  [
    "guilty-pleasure",
    "Guilty Pleasure",
    "challenge",
    "Name a harmless guilty pleasure. Anyone who shares it drinks 1.",
    "a secret snack hidden under a napkin",
  ],
  [
    "would-you-survive",
    "Would You Survive?",
    "challenge",
    "Name a silly disaster. Table votes who survives; chosen gives 1.",
    "a tiny harmless disaster in a snow globe",
  ],
  [
    "make-a-mascot",
    "Table Mascot",
    "challenge",
    "Pick an object as tonight's mascot. Everyone gives it a name.",
    "an ordinary object dressed as a mascot",
  ],
  [
    "secret-handshake",
    "Handshake Deal",
    "challenge",
    "Invent a no-contact handshake with someone. Table judges the finale.",
    "two friends mirroring a funny gesture",
  ],
  [
    "compliment-duel",
    "Compliment Duel",
    "challenge",
    "Trade compliments with a rival. First to laugh drinks 1.",
    "two duelists armed with flowers",
  ],
  [
    "memory-lane",
    "Memory Lane",
    "challenge",
    "Tell a short funny memory with someone here. They correct one detail.",
    "two friends pointing at an old portrait",
  ],
  [
    "unexpected-expert",
    "Ask the Expert",
    "challenge",
    "Table names a silly subject. Give one confident expert answer.",
    "a fake professor at a tiny lectern",
  ],

  // One-card rules, all explicitly expiring on the next reveal.
  [
    "no-first-names",
    "Last Names Only",
    "rule",
    "Until next card: use last names only. Slip = drink 1.",
    "name tags showing only surnames",
  ],
  [
    "royal-we",
    "Royal We",
    "rule",
    "Until next card: say we instead of I. Slip = drink 1.",
    "a tiny crown above a speech scroll",
  ],
  [
    "third-word-cheers",
    "Say Cheers",
    "rule",
    "Until next card: say cheers before drinking. Slip = drink 1.",
    "a cup with a cheers banner",
  ],
  [
    "no-yes",
    "No Yes",
    "rule",
    "Until next card: the word yes is banned. Slip = drink 1.",
    "a crossed-out yes on a parchment",
  ],
  [
    "no-no",
    "No No",
    "rule",
    "Until next card: the word no is banned. Slip = drink 1.",
    "a crossed-out no on a parchment",
  ],
  [
    "no-i",
    "No I",
    "rule",
    "Until next card: the word I is banned. Slip = drink 1.",
    "a single crossed-out letter",
  ],
  [
    "proper-titles",
    "Your Majesty",
    "rule",
    "Until next card: address everyone as Your Majesty. Slip = drink 1.",
    "a row of paper crowns",
  ],
  [
    "pinky-out",
    "Pinky Out",
    "rule",
    "Until next card: pinky out when you sip. Slip = drink 1.",
    "a delicate hand holding a huge tankard",
  ],
  [
    "speak-in-rhyme",
    "Rhyme Crime",
    "rule",
    "Until next card: finish each sentence with a rhyme. Slip = drink 1.",
    "a rhyming scroll tied in a knot",
  ],
  [
    "dramatic-bow",
    "Take a Bow",
    "rule",
    "Until next card: bow before speaking. Slip = drink 1.",
    "an adventurer making an exaggerated bow",
  ],
  [
    "formal-toast",
    "Formal Toast",
    "rule",
    "Until next card: raise your glass before sipping. Slip = drink 1.",
    "a solemn raised goblet",
  ],
  [
    "table-narrator",
    "Narrator Voice",
    "rule",
    "Until next card: narrate your own actions. Slip = drink 1.",
    "a speech scroll following an adventurer",
  ],
  [
    "third-person-toast",
    "Third Person Toast",
    "rule",
    "Until next card: toast in the third person. Slip = drink 1.",
    "a toast scroll written about its speaker",
  ],
  [
    "silent-toast",
    "Silent Toast",
    "rule",
    "Until next card: toast only with gestures. Speak during a toast: drink 1.",
    "friends toasting in complete silence",
  ],
  [
    "question-answer",
    "Answer in Questions",
    "rule",
    "Until next card: answer questions with questions. Slip = drink 1.",
    "two interlocked question marks",
  ],
];

export const standardExpansionCards: CardDefinition[] = drafts.map(
  ([id, title, category, rules, motif]) =>
    card(
      id,
      title,
      category,
      rules,
      `Illustrate ${motif}; one clear focal point, warm fantasy tavern styling.`,
    ),
);
