/**
 * Builds the card-imprint sprite from the vendored game-icons library.
 *
 * Only the slugs the game actually references are compiled in, and the result
 * is a single lazily-imported module — the vendored library itself is never
 * shipped. Run with `npm run imprint`; `scripts/validate-content.ts` also fails
 * the build when the generated file is stale.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { imprintIconSlugs } from "../src/content/imprint";
import { normalizeIcon } from "../src/presentation/imprint/normalize";

const LIBRARY_DIR = "assets/icons/game-icons";
export const IMPRINT_OUTPUT = "src/presentation/imprint/icons.generated.ts";

/** Build the generated module source (also used to detect a stale file). */
export async function buildImprintModule(): Promise<string> {
  const slugs = imprintIconSlugs();
  const entries = await Promise.all(
    slugs.map(async (slug) => {
      const source = await readFile(`${LIBRARY_DIR}/${slug}.svg`, "utf8").catch(
        () => {
          throw Error(
            `Missing vendored icon "${slug}" — check assets/icons/game-icons`,
          );
        },
      );
      return [slug, normalizeIcon(slug, source)] as const;
    }),
  );
  const body = entries
    .map(
      ([slug, geometry]) =>
        `  ${JSON.stringify(slug)}: ${JSON.stringify(geometry)},`,
    )
    .join("\n");
  return `// AUTO-GENERATED by scripts/imprint.ts — do not edit by hand.
// Source: assets/icons/game-icons @ 82d948812bfe3f269ef8f731dcdb07b08160edc4
// Icons made by the game-icons.net contributors, CC BY 3.0 (see docs/licenses).
// Regenerate with \`npm run imprint\` after changing src/content/imprint.ts.

/** Normalized 512x512 SVG geometry per \`<artist>/<icon>\` slug. */
export const imprintIcons: Record<string, string> = {
${body}
};

/** Slugs compiled into this sprite; used by content validation and tests. */
export const imprintSpriteSlugs: readonly string[] = ${JSON.stringify(slugs)};
`;
}

const isMain =
  process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const generated = await buildImprintModule();
  await mkdir(dirname(IMPRINT_OUTPUT), { recursive: true });
  await writeFile(IMPRINT_OUTPUT, generated);
  console.log(
    `Imprint sprite: ${imprintIconSlugs().length} icons → ${IMPRINT_OUTPUT} (${(generated.length / 1024).toFixed(1)} KiB raw).`,
  );
}
