import { format } from "prettier";
import type { PackDefinition } from "../src/game/types";

// Renders `src/content/manifest.generated.ts`: every pack's metadata and card
// IDs, with no card text. The app imports the manifest at startup and loads
// card text per pack only when a game starts (`src/content/loaders.ts`).
export function renderManifest(packs: readonly PackDefinition[]) {
  return format(
    `// Generated by \`npm run content:manifest\` from src/content/catalog.ts.
// Do not edit; the build regenerates it and a unit test checks it is current.
import type { PackDefinition } from "../game/types";

export const packs: PackDefinition[] = ${JSON.stringify(packs)};
`,
    { parser: "typescript" },
  );
}
